### ISSUE TITLE
fix: nightwelding runner bypasses adapter abstraction with hardcoded GitHub calls and drops provider in nested sweep

### ISSUE THREAD

**Issue by ppijbb** [ppijbb/sparkleforge#1407]
> **Date**: 2026-08-15 07:05:46
> **Issue Type**: Sub-issue (Anvil Phase A)
> **Related Milestone**: #13 Anvil
> **Metrics & Justification**: The nightwelding runner is designed to be backend-agnostic via the `BaseNightweldingAdapter` interface (per #1404), yet `runner.py` directly calls `github_adapter.push_branch()` and `github_adapter._run()`. This means any non-GitHub adapter (e.g., `LocalGitAdapter`) will crash with `AttributeError` at runtime when the runner attempts to push changes. Additionally, `run_nightwelding_sweep` omits the `provider` argument when calling `run_nightwelding_issue` for each candidate, causing the inner call to re-invoke `_resolve_adapter` which may select a different adapter than the one already chosen for the sweep — leading to inconsistent backend usage within a single sweep run. Concrete failure path: `LocalGitAdapter` has no `push_branch` method, so any local-mode nightwelding run that reaches the publish step raises `AttributeError: 'LocalGitAdapter' object has no attribute 'push_branch'`.

### 1. Leaky Abstraction — Direct GitHub Calls in Backend-Agnostic Runner

`runner.py` calls `github_adapter.push_branch()` and `github_adapter._run()` directly instead of going through the adapter interface. This violates the pluggable adapter architecture introduced in #1404 and makes the `LocalGitAdapter` non-functional for the publish/push phase.

**Affected code paths:**
- `runner.py` — wherever `push_branch()` is called on the adapter
- `runner.py` — wherever `_run()` is called on the adapter

### 2. `run_nightwelding_sweep` Drops `provider` in Nested Calls

When iterating over candidate issues, `run_nightwelding_sweep` calls `run_nightwelding_issue(adapter=active_adapter)` but does **not** pass `provider`. This causes `run_nightwelding_issue` to fall through to `_resolve_adapter` again, which may:
- Trigger `gh repo view` network calls during auto-detection (fragile in offline/CI environments)
- Select a different adapter than the one already resolved for the sweep

### 3. `LocalGitAdapter.list_candidate_issues` Ignores `backlog_label`

The method accepts a `backlog_label` parameter but returns all `.md` files in the directory regardless. This breaks the contract defined by `BaseNightweldingAdapter` and the CLI defaults, causing the local adapter to process issues that should be filtered out.

### 4. `GitHubAdapter` Silently Drops Non-Numeric `issue_ref`

In `publish_draft_change` and `report_success`, if `issue_ref` is not a digit, the code silently evaluates to `None` or skips execution. This means:
- PRs may open without closing keywords (e.g., `Closes #123`)
- Labels may fail to apply without any error raised
- The user receives a success report despite incomplete operations

## Actionable Fix Plan

1. **Add `push_branch` and `commit_changes` to `BaseNightweldingAdapter`** as abstract methods. Implement them in both `GitHubAdapter` (delegating to `gh` CLI) and `LocalGitAdapter` (using `git` CLI directly). Replace all direct `github_adapter.push_branch()` / `github_adapter._run()` calls in `runner.py` with `adapter.push_branch()` / `adapter.commit_changes()`.

2. **Thread `provider` through `run_nightwelding_sweep` → `run_nightwelding_issue`** calls. If `active_adapter` is already resolved, pass it explicitly and skip re-resolution inside `run_nightwelding_issue`. Add a guard: if `adapter` is provided AND `provider` is provided, use them directly without calling `_resolve_adapter`.

3. **Implement `backlog_label` filtering in `LocalGitAdapter.list_candidate_issues`**. Parse frontmatter or filename conventions (e.g., files containing the label string, or a `labels:` frontmatter field) to filter candidates. If no filtering convention exists for local files, document the expected format and enforce it.

4. **Raise `NightweldingAdapterError` on non-numeric `issue_ref`** in `GitHubAdapter.publish_draft_change` and `report_success` when a closing keyword or label application is expected but `issue_ref` is not a valid issue number. Alternatively, support string-based issue references (e.g., `#abc` for discussion threads) if applicable, but never silently skip.

5. **Add integration tests** that run the nightwelding flow with `LocalGitAdapter` end-to-end (mocked git operations) to prevent regression of the adapter abstraction.

**Comment by ppijbb** [comment]
OpenCode auto-fix PR: https://github.com/ppijbb/sparkleforge/pull/1408

**Comment by ppijbb** [comment]
OpenCode auto-fix failed before a PR could be created.

- Run: https://github.com/ppijbb/sparkleforge/actions/runs/31871149553
- Workflow: OpenCode Auto Fix PR
- Issue: #1407

Worker error:
```text
NVIDIA NIM primary failed (NVIDIA NIM 429: {'status': 429, 'title': 'Too Many Requests'), trying Google or OpenRouter...
Model minimax/minimax-m2.5:free unavailable (OpenRouter 404: This model is unavailable for free. The paid version is availabl), trying fallback...
Model tencent/hy3 unavailable (OpenRouter 402: Insufficient credits. This account never purchased credits. Make), trying fallback...
Model z-ai/glm-5.2 unavailable (OpenRouter 402: Insufficient credits. This account never purchased credits. Make), trying fallback...
Model moonshotai/kimi-k2.5 unavailable (OpenRouter 402: Insufficient credits. This account never purchased credits. Make), trying fallback...
Model minimax/minimax-m3 unavailable (OpenRouter 402: Insufficient credits. This account never purchased credits. Make), trying fallback...
Model qwen/qwen3.7-plus unavailable (OpenRouter 402: Insufficient credits. This account never purchased credits. Make), trying fallback...
Model deepseek/deepseek-v4-flash unavailable (OpenRouter 402: Insufficient credits. This account never purchased credits. Make), trying fallback...
Model google/gemini-3.1-flash-lite unavailable (OpenRouter 402: Insufficient credits. This account never purchased credits. Make), trying fallback...
NVIDIA NIM fallback also failed: NVIDIA NIM 429: {'status': 429, 'title': 'Too Many Requests'}
[patch] Normalised diff paths and hunk headers.
[patch] Whole-patch git apply succeeded.
```

Verification output:
```text
```

**Comment by ppijbb** [comment]
Fix PR #1427 was merged. This issue has been automatically closed.
